### ISSUE TITLE
请问怎么多开？

### ISSUE THREAD

**Issue by oneeeeeeeeeee** [ronething/xiudong-selenium#10]
看您在 #2 中有推荐多开，但是不是很明白怎么操作。是在自动打开的浏览器外，再另外开浏览器吗。但是它好像无法接入程序

**Comment by ronething** [comment]
你只需要复制 main.py 文件，然后改一下端口（例如 9998）运行即可。

**Comment by qilou-0207** [comment]
> 你只需要复制 main.py 文件，然后改一下端口（例如 9998）即可运行。

大佬可以讲一下详细流程吗 为什么我在文件夹复制了main.pyw文件并重命名文件及修改端口后运行到第二个端口会自动关闭第一个端口呢

**Comment by oneeeeeeeeeee** [comment]
> > 你只需要复制 main.py 文件，然后改一下端口（例如 9998）即可运行。
> 
> 大佬可以讲一下详细流程吗 为什么我在文件夹复制了main.pyw文件并重命名文件及修改端口后运行到第二个端口会自动关闭第一个端口呢

你修改了端口之后，新打开的网页也是用新端口的链接啊

**Comment by qilou-0207** [comment]
> > > 你只需要复制 main.py 文件，然后改一下端口（例如 9998）就可以运行了。
> > 
> > 
> > 大佬可以讲详细流程吗？为什么我在文件夹中复制了main.pyw并重命名了修改端口后运行到第二个端口会自动第一个端口呢
> 
> 你修改了今天的端口，新打开的网页也是新端口的链接用啊

可是我刚到运行第二个py的时候就会关闭第一个浏览器窗口 就算不输入链接的情况下也是呢

**Comment by qilou-0207** [comment]
> > > 你只需要复制 main.py 文件，然后改一下端口（例如 9998）就可以运行了。
> > 
> > 
> > 为什么我在文件夹中详细讲了流程吗？
> 
> 你修改了今天的端口，新打开的网页也是新端口的链接用啊

可是我刚跑第二个mian.py的时候就会出现 关闭第一个浏览器窗口并出现新浏览器窗口的情况 这是什么原因呢

**Comment by oneeeeeeeeeee** [comment]
运行了同一个main.py?

**Comment by Redlove2015** [comment]
好像网页只能登一个账号，登录另外一个就会被踢出？请问怎么实现同一个账号抢两个价位的票呢？
