### ISSUE TITLE
貌似现在很难抢了

### ISSUE THREAD

**Issue by jeremy526** [ronething/xiudong-selenium#12]
修改了部分代码 今天尝试着抢了好几场都没有抢到 不知道是票太少还是怎么回事😅

**Comment by ronething** [comment]
一个合理的推测是用脚本的人越来越多(不一定是用我这个)，去年 7 月份的时候很多场次我基本都抢得到。

还有一个就是官方加强了一些对抗策略。

即然有相关的开发能力，也许你可以尝试一下 js 逆向，理论上成功率会有所提高。就这样，祝你好运哦～

**Comment by jeremy526** [comment]
是的 js逆向永远是最优的解决方式
