### ISSUE TITLE
不支持自动选中观演人

### ISSUE THREAD

**Issue by Ohihahaha** [ronething/xiudong-selenium#15]
夏企6.10广州场的时候，需要绑定观演人才能抢票。
每次刷到票之后，没有办法直接生成订单，反而一直刷新，同时提示”请选择观演人“，但是因为一直刷新又无法选择。

**Comment by ronething** [comment]
是的，目前并没有支持选择自动绑定观演人。如果你有开发能力，可以考虑研究一下然后提一下 pr。

**Comment by ronething** [comment]
可以参考 #19 ，不过逻辑可能需要自己稍作修改(参见 review)
