### ISSUE TITLE
开始抢票后不停跳出”填写观演人“

### ISSUE THREAD

**Issue by Liuliaoliao11** [ronething/xiudong-selenium#21]
![屏幕截图 2022-06-10 161457](https://user-images.githubusercontent.com/107175742/173029124-510d4a29-4dbc-4090-99c5-26e78ac7274b.jpg)
我将”http://127.0.0.1:9997/buy?event=172472&ticketId=cc98d529b4ddc6973dc4fbf36cc83b9c“复制到 新的窗口后开始抢票，页面不停刷新，但是不停跳出”填写观演人“，导致无法进行抢票。求大佬，这个怎么解决？

**Comment by ronething** [comment]
可以参考 https://github.com/ronething/xiudong-selenium/pull/19 ，不过逻辑可能需要自己稍作修改(参见 review)
