### ISSUE TITLE
[feat] 需要选择观演人的场次支持

### ISSUE THREAD

**Issue by ronething** [ronething/xiudong-selenium#22]
1、手动标识是否需要选择观演人，默认不选择
2、如果需要选择观演人，可以指定需要选择的人数，默认选择一个

使用方法请看 readme 或者直接看代码

~~目前暂时未打算实现，未通用的版本可考虑参考 #19~~

~~期待一个师傅提交 pr~~

**Comment by oneeeeeeeeeee** [comment]
我改进的是
1.判断是否需要选择，判断为否，不执行
2.如果判断需要选择，则点击全选。
我认为帐号提前设置好和票数对应的观演人，然后全选比较快。

**Comment by ronething** [comment]
> 1.判断是否需要选择，判断为否，不执行

你想通过什么进行判断。

**Comment by oneeeeeeeeeee** [comment]
> > 1.判断是否需要选择，判断为否，不执行
> 
> 你想通过什么进行判断。

 我自己的用的已经实现了，但是因为达不到您在 #19 中所说的要求，所以没提PR
因为我是在进入页面后就通过try语法，去尝试定位选择观演人的这个网页元素。定位到了就执行选择观演人的操作，定位不到就打印不需要观演人，当然这句话会在不需要选择身份证的捡漏刷新时不断被重复，可以省掉，只是为了当初看代码是不是正常运行所设置的。
完成了上述操作后才去执行是否到时间点击购买或刷新网页。

**Comment by ronething** [comment]
之所以考虑手动指定是否需要观演人，是为了不需要观演人的情况下，节省那一点寻找元素的时间。

通过 try 不是不行，就是这部分时间被算进去了，抢到票的概率理论上更低一些。

**Comment by oneeeeeeeeeee** [comment]
> 之所以考虑手动指定是否需要观演人，是为了不需要观演人的情况下，节省那一点寻找元素的时间。
> 
> 通过 try 不是不行，就是这部分时间被算进去了，抢到票的概率理论上更低一些。

所以暂时也达不到要求提PR[捂脸]
主要是手动指定也很麻烦，我们就得提前先进去看一遍购票是否需要，才能在程序上指定。这个步骤我觉得挺麻烦的。

**Comment by ronething** [comment]
> 我们就得提前先进去看一遍购票是否需要

其实是可以不需要的，ticket 票种相关返回有对应字段标识。

也许我应该考虑开发一个简单的 web 页面而不是单纯的 http api，有机会的话。

**Comment by oneeeeeeeeeee** [comment]
> > 我们就得提前先进去看一遍购票是否需要
> 
> 其实是可以不需要的，ticket 票种相关返回理论上有对应字段标识。
> 
> 也许我应该考虑开发一个简单的 web 页面而不是单纯的 http api，有机会的话。

有时间的话 我看看怎么再获取票种的地方对应看看字段是否又判断观演人

**Comment by ronething** [comment]
@oneeeeeeeeeee Hello, 有空可以考虑测试下 更新了自动选择观演人。readme 中有说明传参，会根据需要的人数自动按顺序进行选择。

**Comment by oneeeeeeeeeee** [comment]
> @oneeeeeeeeeee Hello, 有空可以考虑测试下 更新了自动选择观演人。readme 中有说明传参，会根据需要的人数自动按顺序进行选择。

好的，有空我试试

**Comment by oneeeeeeeeeee** [comment]
刚才试了一下，没什么问题。False就不选，True就按输入的人数选择。不过好像选择速度有点慢。

**Comment by ronething** [comment]
嗯。因为需要先打开观演人列表，然后再进行一个一个选择。模拟点击可能差不多就是这样的速度。

**Comment by oneeeeeeeeeee** [comment]
我觉得是元素查找的问题，因为我之前做的点击个人感受是比你的快一点点[捂脸]
就是现在用你的，会有停顿的感觉。可能是显性等待的问题。
我用的是直接driver.findelements

**Comment by ronething** [comment]
可以，不如你改成  find elements，然后和 wait.util 打印下元素选择时间对比测试下？

**Comment by oneeeeeeeeeee** [comment]
有道理 我试一下

**Comment by oneeeeeeeeeee** [comment]
确实会稍微快一点点
我在选择观演人的前后打上时间戳 然后打印出来
您的代码耗时0.9s
![QQ截图20220618174225](https://user-images.githubusercontent.com/105046609/174432837-0c538ce8-3675-4cd2-a1ee-d2ee8deb3c3e.png)
我的耗时0.8s
![QQ截图20220618175953](https://user-images.githubusercontent.com/105046609/174432852-9e3e62f5-15d0-478f-85cf-3633dbbb4fee.png)

同一个抢票页面 同一个帐号测试的

**Comment by oneeeeeeeeeee** [comment]
这是我的代码，因为没专门设一个选择的函数，所以直接用的
`start_clock = time.time()`
`    try:`
`        pleaseSelect = driver.find_element_by_css_selector('.info-item.link-item')`
`    except:`
`        print('不需要观演人')`
`    else:`
`        if '观演人' in pleaseSelect.text:`
`            pleaseSelect.click()`
`            time.sleep(0.1)`
`            checkBoxs = driver.find_elements_by_css_selector('.uni-checkbox-wrapper')`
`            for checkBox in checkBoxs:`
`                checkBox.click()`
`            time.sleep(0.1)`
`            confirm = driver.find_element_by_css_selector('.pop-box>.pop-head>uni-view:nth-child(2)')`
`            time.sleep(0.1)`
`            confirm.click()`
`      end_clock = time.time()`
`    print(f'耗时:{end_clock - start_clock}')`

这是您的代码，您参考下
`start_clock = time.time()`
`        select_people(driver=chrome_driver, num=int(select_num))`
`        end_clock = time.time()`
`        print(f'耗时:{end_clock - start_clock}')`

**Comment by ronething** [comment]
好 我有空再看看。不过还要多次进行测试下。

**Comment by ronething** [comment]
先 close
