### ISSUE TITLE
请教一下这是为什么呢

### ISSUE THREAD

**Issue by Jackpzzz** [ronething/xiudong-selenium#25]
![image](https://user-images.githubusercontent.com/106529017/173780053-c0815b47-97ee-4866-8074-90acfa90da4d.png)

**Comment by Jackpzzz** [comment]
![image](https://user-images.githubusercontent.com/106529017/173791790-8955f0e7-7d2f-4c9a-a179-871c3352d53f.png)
请问我新开一个系统的浏览器访问 http://127.0.0.1:9997/login 直接弹出这个界面然后怎么办呢

**Comment by ronething** [comment]
基本的使用问题可以考虑参考下 #3 以及 #5 ，看完有新的问题可以考虑提 issue，谢谢。
