### ISSUE TITLE
请问一下这种必须要打开app购买的是不是不能用脚本抢啊  其他的右下角都是立即购买

### ISSUE THREAD

**Issue by Jackpzzz** [ronething/xiudong-selenium#27]
![image](https://user-images.githubusercontent.com/106529017/173816980-3f2b8ba1-9243-4c03-8751-74a8afbfacca.png)

**Comment by ronething** [comment]
基本的使用问题可以考虑参考下 https://github.com/ronething/xiudong-selenium/issues/3 以及 https://github.com/ronething/xiudong-selenium/issues/5 ，看完有新的问题可以考虑提 issue，谢谢。
