### ISSUE TITLE
请问一下 这是什么问题 是我的chromedrive路径不对吗 无法正确加载出login界面

### ISSUE THREAD

**Issue by neophobia1776** [ronething/xiudong-selenium#28]
[
![2022-06-17_154814](https://user-images.githubusercontent.com/107673853/174252476-6190db1c-d720-4d36-a2eb-50406bc0bf49.jpg)
![2022-06-17_154904](https://user-images.githubusercontent.com/107673853/174252512-8340cb57-0c7b-4109-ac5a-8f28fe05470a.jpg)
](url)

**Comment by ronething** [comment]
不是路径不对的问题，你已经跑起来了。可以看一下 #3 ，更多的内容可以看 #5，需要请求对应 api，有问题再提 issue，谢谢。
