### ISSUE TITLE
[chore] 使用问题交流

### ISSUE THREAD

**Issue by smallpang** [ronething/xiudong-selenium#3]
python不太了解，我现在能唤起chrome，但是出来之后，不跳转到登录页面，应该怎么弄呀？希望大佬能解答一下，我很菜，如果不嫌弃就我就好。Orz...
![TWXRT89I_V%N}{LQF5D8E1V](https://user-images.githubusercontent.com/33652387/164711946-ff4d48ac-70d7-45dc-93d1-4b85791da082.png)

**Comment by ronething** [comment]
你可以新开一个系统的浏览器，访问 127.0.0.1:9997/login，就会跳转到登录页面了。

**Comment by ronething** [comment]
其实跟 python 不 python 没啥关系，我只是暴露一个 http 服务出来，你访问对应接口就行了。可以看看 readme

**Comment by smallpang** [comment]
好像会了点，感谢大佬！！！！其实就是我比较菜，又想看演出....哈哈哈哈哈谢谢大佬解答！！对了，还有一个问题，那些还没开售的票，应该怎么给他event和ticketid的值呢？那个购票按钮无法点击。。。大佬方便留下一个联系方式吗？昨晚其实我第一时间看到了你的回复，但是当时没有电脑，就没上github回复，如果能给个联系方式，我立马加上，然后关闭issue。

**Comment by ronething** [comment]
哈哈哈 不是大佬 有问题提 issue 就好了 方便问题记录沉淀。event 是 url 中的 activityID，ticketid 需要点击立即购买然后通过浏览器开发者工具抓包看到。有一些场次是要求 app 内购买，不过其实也是可以获取到的。这部分有时间再补充吧。

那联系方式暂时不给了 人多一点之后可以考虑建一个 slack 群组。

**Comment by smallpang** [comment]
我问一下哈，这个流程是不是这样子的：提前将event和ticketID的值输入到driver.py里confirm_url中，修改那个抢票时间，运行main.py，然后输入账号、验证码就行了，脚本会自动就会自动运行嘛？（但是好像不行，我找了一个还在售票的演出，我把ticketid写死，会报错...如果不是这样，那应该在哪里给event和ticketid的值呢？main里面也没有调用这个函数的,,,）
![image](https://user-images.githubusercontent.com/33652387/164878008-7faac564-a18c-4a0f-9789-db5de5acbf4b.png)

然后event我是可以看到的，但是ticketid我还是无法获取到，因为那些票都还没有开售，立即购买点不了，而且我按F12，去elements和source里也没找到这个值...

**Comment by ronething** [comment]
不需要修改代码里面的值哦。你调用 login 接口登陆之后 可以再调用 buy 接口传入 event 和 ticketId，形如 http://127.0.0.1:9997/buy?event=111&ticketId=222

还有，你改了代码之所以报错 是因为语法错了。

｛｝里面不是填具体的值，如果要填具体的值 应该把花括号也去掉。可以搜一下 python3 format 格式化使用。

**Comment by smallpang** [comment]
所以这个不是自动的是嘛？因为我登录了之后需要，再调用buy接口，然后更改我之前所得到的event和ticketid，如果抢到了，就会进入显示立即支付的页面，是这个样子吗？对了，ticketid怎么通过浏览器开发者工具抓包看到哇？y我没找到...因为还没开票的演出无法出现立即支付。。。希望大佬不要介意我的这些低级问题。。QAQ

**Comment by ronething** [comment]
> 所以这个不是自动的是嘛？因为我登录了之后需要，再调用buy接口，然后更改我之前所得到的event和ticketid，

event 和 ticketid 需要自己获取然后传入。前面说了，这个脚本 只是暴露出一个 http 服务以供调用。你要改自动的其实就是那种脚本写好，第一步登录之后，**等待登录完成**，然后自动跳转到下单页面进行下单。我只是把这两步拆分出来作为 http 服务提供而已。

调用 bug 接口会到达下单页面，然后到点(如果设置了定时的话)自动下单，类似这样，然后就可以挂着了。

<img width="418" alt="image" src="https://user-images.githubusercontent.com/28869910/164878726-d98583d6-f695-468c-a583-7e06f9859d6a.png">

> 如果抢到了，就会进入显示立即支付的页面

如果抢到了，界面会如同 readme 那样(弹出让你支付的界面)，此时你可以在 app 上进行支付即可。

**Comment by ronething** [comment]
> 因为还没开票的演出无法出现立即支付

不要到达立即支付那一步，你点击立即购买的时候，票种列表的接口响应已经就有了。可以看一下包的响应。相信你可以找到。

**Comment by smallpang** [comment]
还是找不到。。。。我点击了立即购买，想试着在elements里搜搜看，有没有ticketid，但是只找到了这个ticketIndex，我以为在Sources里那些文件里，去找，还是没找到。。。大佬能再shuo说详细点嘛？十分感谢！！！Orz...
![image](https://user-images.githubusercontent.com/33652387/164882251-07be8a3a-5473-4430-b086-ebc13b8ecb4c.png)

**Comment by ronething** [comment]
> 想试着在elements里搜搜看，有没有ticketid，但是只找到了这个ticketIndex，我以为在Sources里那些文件里，去找，还是没找到

<img width="99" alt="image" src="https://user-images.githubusercontent.com/28869910/164882648-86940534-f58c-425b-b394-945fff3f1e7b.png">

在 network 里面哦

**Comment by smallpang** [comment]
我找是找到了ticketid，可是没有具体的值...这种应该怎么办呐？
![image](https://user-images.githubusercontent.com/33652387/164882916-c1f3d970-5d92-4a0c-b2d6-fa22411bdb3f.png)

**Comment by ronething** [comment]
你这个是 js， 你应该点 xhr，点击立即购买，会产生新的包，可以再看一下。

<img width="89" alt="image" src="https://user-images.githubusercontent.com/28869910/164883746-70c855d0-3d4c-43bf-ade1-7db3567f8be8.png">

**Comment by smallpang** [comment]
卧槽，进来了！！！！谢谢大佬！！！是不是只要再更改这个开始时间，就可以变成到点抢票了？
![image](https://user-images.githubusercontent.com/33652387/164884261-5b5aff06-dc4c-4be5-8061-ae6b79906964.png)

**Comment by smallpang** [comment]
还有最后一个问题，如果想两三个账号同时抢的话，是不是只要在浏览器开两三个窗口，登录各个账号，重复之前的步骤，在这个立即支付的界面等待时间到就好了？

**Comment by smallpang** [comment]
谢谢大佬，虽然没抢到下午康姆士的票，还好收到了，而且受益匪浅，哈哈哈哈哈谢谢大佬花这么时间指点我，要不发一个收款码，我感激一下！！！

**Comment by ronething** [comment]
呜呜 没抢到实在可惜 有收到就好。哈哈哈 收款码就不用了(等你下次抢到再赞赏也不迟)，可以看看代码有什么可以改进的地方，提提 pr，一起交流。

**Comment by smallpang** [comment]
我也不是很懂哈哈哈哈哈，都是大佬牛逼！

**Comment by rookieyjh** [comment]
老哥 你写的东西怎么一步步唤醒 我现在完全不会用 能教一下吗

**Comment by ronething** [comment]
建议掌握基本编程基础之后然后再回来看这个 issue 你就会用了 感恩。

**Comment by rookieyjh** [comment]
有没有速通的方法呀大佬，这两天广州live很多 一张抢不到😭



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ashing ***@***.***&gt;
发送时间: 2022年4月26日 19:46
收件人: ronething/xiudong-selenium ***@***.***&gt;
抄送: rookieyjh ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ronething/xiudong-selenium] [chore] 使用问题交流 (Issue #3)





 
建议掌握基本编程基础之后然后再回来看这个 issue 你就会用了 感恩。

**Comment by ronething** [comment]
我先 close 了。有问题再开 issue

**Comment by Liuliaoliao11** [comment]
> python不太了解，我现在能唤起chrome，但是出来之后，不跳转到登录页面，应该怎么弄呀？希望大佬能解答一下，我很菜，如果不嫌弃就我就好。Orz... ![TWXRT89I_V%N}{LQF5D8E1V](https://user-images.githubusercontent.com/33652387/164711946-ff4d48ac-70d7-45dc-93d1-4b85791da082.png)

您好！这个问题怎么解决的啊？我也是到这步，不跳转到登录页面。求解

**Comment by NamelessAshone** [comment]
请问app内购买的票怎么获取tickid

**Comment by chsyts** [comment]
up 你好 我的打不开浏览器 报错 FLASK_APP = main.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder C:/Users/anyi/PycharmProjects/xiudong-selenium-main
D:\ProgramData\Anaconda3\python.exe -m flask run
 * Serving Flask app 'main.py' (lazy loading)
 * Environment: development
 * Debug mode: off
Usage: __main__.py run [OPTIONS]

Error: Detected factory 'create_app' in module 'xiudong-selenium-main.main', but could not call it without arguments. Use "FLASK_APP='xiudong-selenium-main.main:create_app(args)'" to specify arguments.

**Comment by rascal7x** [comment]
你好我本地windows正常运行，并且尝试了购票也成功了。但是我现在想部署到我的linux服务器，现在是成功启动了。我想问的是如何实现登录呢，我的linux是没有图形界面的，是必须需要装图形界面才能实现登录功能吗？就是登录接口是否能以参数的形式调用？

**Comment by ZPPengZhou** [comment]
请问打印“获取到立即支付按钮”之后是会自动选择观影人吗？这时候正式开始抢票？还需要别的操作吗？
