### ISSUE TITLE
TickId请问如何获取

### ISSUE THREAD

**Issue by NamelessAshone** [ronething/xiudong-selenium#30]
Hi, ronething
我想抢康姆士成都场的票，目前没有开放预售，请问是要预售后才能获取ticketid吗？
还有支付方式如何解决？

另外，非常感谢您的项目！
如果需要，提供下支持的渠道，我的个人邮箱是lambda.ssx@aliyun.com（规避法律风险，可以私发我）

**Comment by Redlove2015** [comment]
看到了也更新一下，目前我搜集到ticketid的方法是，

以该链接https://www.showstart.com/event/172085为例

打开后按F12，在script的地方，显示的是以下的内容，看了一下，内容是另外的活动的，CTRL+F查找"TICKET"查找不到东西。
页面刷新一下，这时候script就会刷新到当前活动的，此时查找ticket就能查找到ID

window.__NUXT__=(function(a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,_,$){return {layout:"default",data:[{home:{banners:[{id:387324,activityId:s,sequence:s,type:d,path:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0612\u002F03\u002F30\u002F808af3967db7481fa0dd92028bdc425b_1200_400_390078.0x0.png",title:"Fine",url:"https:\u002F\u002Fwww.showstart.com\u002Fevent\u002F176119"},{id:387853,activityId:"40848",type:a,path:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0614\u002F11\u002F30\u002Ffa32da8da46241fca00b58deace2ec41_1200_400_1036639.0x0.png",title:"来福好事",url:"https:\u002F\u002Fwww.showstart.com\u002Fevent\u002Flist?type=1&tag=40848",backgroundColor:t},{id:390096,activityId:u,sequence:u,type:d,path:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0621\u002F18\u002F00\u002Fbb049c64ab6e410b83385d13e6215c06_1200_400_888359.0x0.png",title:"商部",url:"https:\u002F\u002Fwww.showstart.com\u002Fevent\u002F172699"},{id:390782,activityId:"40917",type:a,path:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0621\u002F11\u002F30\u002F63ffa5e525444d348e55e4176f38c1bc_1200_400_343227.0x0.png",title:"张颜齐",url:"https:\u002F\u002Fwww.showstart.com\u002Fevent\u002Flist?type=1&tag=40917",backgroundColor:t}],activitys:[{id:v,title:w,poster:x,isExclusive:a,performers:h,price:y,showTime:z,siteName:e,cityName:b,isGroup:c,soldOut:d},{id:A,title:B,poster:C,isExclusive:a,performers:h,price:f,showTime:k,siteName:e,cityName:b,isGroup:c,soldOut:d},{id:D,title:E,poster:F,isExclusive:a,performers:G,price:H,showTime:k,siteName:g,cityName:b,isGroup:c,soldOut:a},{id:176733,title:"“天空之城”-久石让&宫崎骏动漫经典音乐作品演奏会",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F0730\u002F14\u002F30\u002F9b47d615533342599f0e0e300ae201c6_1200_1600_2714725.0x0.png",isExclusive:d,performers:m,price:n,showTime:"2022\u002F07\u002F02 10:30",siteName:o,cityName:b,isGroup:c,soldOut:a},{id:176911,title:"《卡农 Canon In D》永恒经典名曲精选音乐会",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F0729\u002F15\u002F30\u002F7daadbc54eaa4c449efa39b62423157e_1200_1600_1688306.0x0.png",isExclusive:d,performers:m,price:n,showTime:"2022\u002F07\u002F02 14:00",siteName:o,cityName:b,isGroup:c,soldOut:a},{id:176795,title:"“爱乐之城”——经典电影音乐作品音乐会",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F0729\u002F14\u002F00\u002Fd700945e6de44e668acbbf8a8d3e18b9_1200_1600_1818773.0x0.png",isExclusive:d,performers:m,price:n,showTime:I,siteName:o,cityName:b,isGroup:c,soldOut:a},{id:173513,title:"唐诗逸领衔主演-鸿篇巨制.大型民族舞剧《昭君》",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0408\u002F09\u002F00\u002F969b604f955b4713ac7bfab19c9170bb_1200_1600_2975824.0x0.png",isExclusive:d,performers:"唐诗逸",price:"¥380起",showTime:I,siteName:"北京展览馆剧场",cityName:b,isGroup:c,soldOut:a},{id:J,title:K,poster:L,isExclusive:d,performers:M,price:N,showTime:O,siteName:i,cityName:b,isGroup:c,soldOut:a},{id:P,title:Q,poster:R,isExclusive:d,performers:S,price:f,showTime:T,siteName:e,cityName:b,isGroup:c,soldOut:a},{id:U,title:V,poster:W,isExclusive:a,performers:X,price:Y,showTime:Z,siteName:g,cityName:b,isGroup:c,soldOut:a}],performers:[{id:2705,name:h,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2018\u002F20181128\u002Fe10e701d2fa84d83b8db9a8a17964ea2_190_190_4016.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2020\u002F1113\u002F18\u002F30\u002Fc12f07823d4e464e8a1293cfd0ae5db8_1280_900_253465.0x0.jpg"},{id:3021892,name:"硬核喜剧",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2019\u002F20190909\u002F463705eaf8c64fceb4022803632e4a4b_500_500_337884.0x0.jpg"},{id:6730944,name:"大笑喜剧",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0221\u002F14\u002F00\u002F0f5a1ab27767449c834a6a92eac708cf_800_800_683271.0x0.png"},{id:6994885,name:"笑脱喜剧工作室",avatar:j},{id:4048029,name:"玩脱喜剧团队",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2020\u002F0909\u002F17\u002F30\u002F12a28dbcd1e6458788f122ea1b6a8272_185_185_30781.0x0.jpg"},{id:3784766,name:"神秘嘉宾（脱口秀）",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2020\u002F0810\u002F11\u002F00\u002F5efda111134c443181f77e5d1bcd3925_190_190_86863.0x0.jpg"},{id:25300,name:"待定",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fgroup1\u002FM00\u002F05\u002F58\u002FChQyH1ZO1S-AWOhzAABfuAL1jxk379.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2019\u002F20190110\u002Fce5f68d13225441c978accedbc038646_1280_900_183587.0x0.jpg"},{id:4987,name:"测试艺人账号",avatar:"https:\u002F\u002Fs2.showstart.com\u002Fgroup1\u002FM00\u002F00\u002F27\u002FChQyH1Sc2dmAabgqAABDnL_embE067.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2020\u002F20200409\u002F03ba989eefc94aa484c0f0ec53895699_1280_900_1261209.0x0.jpg"},{id:6914998,name:"于师傅",avatar:j},{id:7987362,name:"陈开心",avatar:j},{id:8208609,name:"金鹏",avatar:j},{id:8208594,name:"郎琪",avatar:j}],sites:[{id:3452,name:l,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fqn_4f43283cb0ab4d99b9f333aa54262826_161_161_67638.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fgroup2\u002FM00\u002F02\u002F1D\u002FChQyIFV2qbKAC9kgAAFBMC2vmx8041.0x0.jpg",cityName:b,address:"北京东城区和平西街79号",latitude:39.956908,longitude:116.422172,qualificationLicense:"https:\u002F\u002Fwap.showstart.com\u002Fpages\u002Fsite\u002Flicense\u002Flicense?userId=3452",activityNum:c,activities:[{id:165402,title:"与牠同行 TOGETHER FOR ANIMALS IN CHINA 第八届公益演唱会",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F1020\u002F13\u002F00\u002Fe3d420a0615e4759ac3a4295aed89f7c_1200_1600_1983252.0x0.png",isExclusive:a,performers:"郝云\u002F白皮书\u002FJoyside\u002FElfKing",price:"¥240起",showTime:"2021\u002F10\u002F27 20:00",siteName:l,cityName:b,isGroup:c,soldOut:a},{id:163076,title:"寸铁巡演 北京站",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F0924\u002F15\u002F00\u002F0f9e9318b72d44b8879e17ed46adfa96_1200_1600_234603.0x0.png",isExclusive:a,performers:"寸铁",price:"¥250",showTime:"2021\u002F10\u002F23 20:30",siteName:l,cityName:b,isGroup:c,soldOut:a},{id:160604,title:"「别忘了 Don’t Forget」尚士达 2021 LIVE TOUR 北京站",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2021\u002F0901\u002F15\u002F30\u002F55e370c1824244ffa175a016969904c1_1200_1600_1340400.0x0.png",isExclusive:d,performers:"尚士达",price:"¥220",showTime:"2021\u002F10\u002F22 20:00",siteName:l,cityName:b,isGroup:c,soldOut:a}]},{id:434180,name:e,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fqn_5a6d6493bb0c4c9895454aa3a2e63eed_190_190_10275.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fqn_9af30f3a7bcc411fbead586c6135e5d7_1280_899_2072165.0x0.jpg",cityName:b,address:"海淀区复兴路69号院2号136-G23Mao livehouse",latitude:39.916375,longitude:116.28377,qualificationLicense:"https:\u002F\u002Fwap.showstart.com\u002Fpages\u002Fsite\u002Flicense\u002Flicense?userId=434180",activityNum:8,activities:[{id:v,title:w,poster:x,isExclusive:a,performers:h,price:y,showTime:z,siteName:e,cityName:b,isGroup:c,soldOut:d},{id:A,title:B,poster:C,isExclusive:a,performers:h,price:f,showTime:k,siteName:e,cityName:b,isGroup:c,soldOut:d},{id:P,title:Q,poster:R,isExclusive:d,performers:S,price:f,showTime:T,siteName:e,cityName:b,isGroup:c,soldOut:a}]},{id:113676,name:g,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fqn_d2a6bae826854b369c502052db1dbc66_190_190_9458.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fqn_a3cdd223207c438a8a7f5d7383378400_1280_900_225211.0x0.jpg",cityName:b,address:"北京市西城区天桥南大街9号天桥艺术中心b103疆进酒OMNI SPACE",latitude:39.888843,longitude:116.404442,qualificationLicense:"https:\u002F\u002Fwap.showstart.com\u002Fpages\u002Fsite\u002Flicense\u002Flicense?userId=113676",activityNum:12,activities:[{id:D,title:E,poster:F,isExclusive:a,performers:G,price:H,showTime:k,siteName:g,cityName:b,isGroup:c,soldOut:a},{id:U,title:V,poster:W,isExclusive:a,performers:X,price:Y,showTime:Z,siteName:g,cityName:b,isGroup:c,soldOut:a},{id:173498,title:"施鑫文月「望江公子」巡演 - 北京站",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0414\u002F19\u002F30\u002F3674d792fbfb4ee5ae6866029ac4b76a_1200_1600_3050319.0x0.png",isExclusive:d,performers:"小老虎J-Fever\u002F施鑫文月\u002F鱼翅Fin",price:f,showTime:"2022\u002F07\u002F14 20:00",siteName:g,cityName:b,isGroup:c,soldOut:a}]},{id:106828,name:i,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fgroup1\u002FM00\u002F11\u002F3D\u002FChQyH1fJUEeABd7lAAJwXBUMDi4576.0x0.jpg",poster:"https:\u002F\u002Fs2.showstart.com\u002Fgroup1\u002FM00\u002F11\u002F3D\u002FChQyH1fJUFKAcG-bAAEY7nVf5wc647.0x0.jpg",cityName:b,address:"北新桥板桥南巷人美大厦北1层乐空间",latitude:39.945197,longitude:116.423978,qualificationLicense:"https:\u002F\u002Fwap.showstart.com\u002Fpages\u002Fsite\u002Flicense\u002Flicense?userId=106828",activityNum:3,activities:[{id:J,title:K,poster:L,isExclusive:d,performers:M,price:N,showTime:O,siteName:i,cityName:b,isGroup:c,soldOut:a},{id:174296,title:"2022刘大壮“会不会”巡演2.0—北京站",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0608\u002F11\u002F30\u002F6f3a3db7b02f4c9b9dc3199281f8581a_1200_1600_2226382.0x0.png",isExclusive:d,performers:"刘大壮",price:"¥168起",showTime:"2022\u002F07\u002F10 20:00",siteName:i,cityName:b,isGroup:c,soldOut:a},{id:173603,title:"2022 Quark\u002F夸克 乐队 十周年暨「永乐宫」新专辑巡演 北京站",poster:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2022\u002F0411\u002F17\u002F00\u002Fd6ced3d8ce4643ddab2e0d13b93fb054_1200_1600_2685592.0x0.png",isExclusive:a,performers:"Quark\u002F夸克乐队",price:f,showTime:"2022\u002F09\u002F23 20:30",siteName:i,cityName:b,isGroup:c,soldOut:a}]},{id:3582934,name:p,avatar:"https:\u002F\u002Fs2.showstart.com\u002Fimg\u002F2020\u002F0807\u002F14\u002F30\u002F20dce4a1e7c04759aaef5c0ca76d1efb_298_298_8127.0x0.jpg",cityName:b,address:"秀动直播间",latitude:39.948717,longitude:116.461047,qualificationLicense:"https:\u002F\u002Fwap.showstart.com\u002Fpages\u002Fsite\u002Flicense\u002Flicense?userId=3582934",activityNum:c,activities:[{id:138251,title:"5.3 【流行金曲嘉年华】秀动线…
