### ISSUE TITLE
测试您新版代码的时候，发现不会点击立即支付，不知道什么问题

### ISSUE THREAD

**Issue by oneeeeeeeeeee** [ronething/xiudong-selenium#31]
![image](https://user-images.githubusercontent.com/105046609/174718150-79f68540-6545-4f89-a9d7-009ae857e55f.png)
不管我设不设抢票时间，它都在检测到立即支付之后，就没反应了，不点击按钮了。
正常应该是会打印开始抢票，然后点击，重启测试几次都不点击了。找的网页是可以直接买票的。不知道什么问题

**Comment by oneeeeeeeeeee** [comment]
好像是在if need_select这个判断上卡住了

**Comment by oneeeeeeeeeee** [comment]
哦 知道了 cron_time如果不传的话 不会执行下面的点击，是时间判断的问题。

**Comment by oneeeeeeeeeee** [comment]
但我前几次传了也没点击 不太清楚什么情况[捂脸]

**Comment by oneeeeeeeeeee** [comment]
> 你应该把 cron_time 的 key 直接不传，cron_time= 的话 获取到的是空字符串而不是 None
> 
> ```
>     if start_time is None:  # 直接抢
>         print(f'开始抢票')
>         confirm_ticket(pay_btn)
> ```
> 
> 这个判断条件就要改。
> 
> 例如改成 `if not start_time:`

![image](https://user-images.githubusercontent.com/105046609/174757402-1a83c64c-439c-4fd1-832e-c7159fc70fbc.png)
但我第一次传了时间还是没有点击不知道什么原因，传的时间是2022 06 21 12 00 00
当时时间是超过12点了的
后面会点击那会传的是2022 06 13 13 00 00
我看看还能不能复现

**Comment by oneeeeeeeeeee** [comment]
http://127.0.0.1:9990/buy?event=174794&ticketId=eebaa243e36685f55dd0191a1112994a&need_select=False&ticketNum=1&select_num=1&cron_time=2022 06 21 12 00 00

奇怪 这样就不行，您试一下？
我一开始是以为我那里不小心动了代码造成的，刚才重新git clone了一份然后运行的这一段还是不行，就是不点，把时间改了也没用，具体原因不清楚

**Comment by ronething** [comment]
这里面可能我 readme 描述不太清晰，need_select 的值无论传什么，都会默认需要选择观演人，这一点你看代码就会知道。所以如果是不需要观演人的场次，传入 need_select 的话，我并没有在 select_people 中进行 try catch 导致无法抛出异常。

你应该把 need_select 参数去除再传即可。后面我再看看怎么优化比较好。

**Comment by oneeeeeeeeeee** [comment]
> 这里面可能我 readme 描述不太清晰，need_select 的值无论传什么，都会默认需要选择观演人，这一点你看代码就会知道。所以如果是不需要观演人的场次，传入 need_select 的话，我并没有在 select_people 中进行 try catch 导致无法抛出异常。
> 
> 你应该把 need_select 参数去除再传即可。后面我再看看怎么优化比较好。

那按我理解
把它改成这样应该就行了吧
`   if need_select: == True`
`        select_people(driver=chrome_driver, num=int(select_num))
`

**Comment by ronething** [comment]
合乎逻辑即可，还有就是注意区分 need_select 获取到的是 str 类型，True 和 'True' 是不同的。

**Comment by oneeeeeeeeeee** [comment]
> 合乎逻辑即可，还有就是注意区分 need_select 获取到的是 str 类型，True 和 'True' 是不同的。

字符类型好像对这个True影响不大，我试试。因为我这么写好像是正常运行了。之前倒确实遇到过字符类型的问题[捂脸]

**Comment by oneeeeeeeeeee** [comment]
您这样一提醒，把我一直想不通的问题开窍了，受教了
