### ISSUE TITLE
linux环境如何实现登录？

### ISSUE THREAD

**Issue by rascal7x** [ronething/xiudong-selenium#32]
你好我本地windows正常运行，并且尝试了购票也成功了。但是我现在想部署到我的linux服务器，现在是成功启动了。我想问的是如何实现登录呢，我的linux是没有图形界面的，是必须需要装图形界面才能实现登录功能吗？就是登录接口是否能以参数的形式调用？

**Comment by rookieyjh** [comment]
您好 请问能给一个windows运行的教程以及文件吗 我真的好想抢到演出

**Comment by rookieyjh** [comment]
> 你好我本地windows正常运行，并且尝试了购票也成功了。但是我现在想部署到我的linux服务器，现在是成功启动了。我想问的是如何实现登录呢，我的linux是没有图形界面的，是必须需要装图形界面才能实现登录功能吗？就是登录接口是否能以参数的形式调用？

您好 请问能给一个windows运行的教程以及文件吗  真的很想抢到票 感谢

**Comment by rascal7x** [comment]
![image](https://user-images.githubusercontent.com/46894020/175199686-f36ddf0f-60b8-404f-8cfc-7a9889a36c99.png)
如果直接调接口就只返回个login ok, 调购买接口返回buy ok 但是实际上是没有成功的

**Comment by rascal7x** [comment]
> > 你好我本地windows正常运行，并且尝试了购票也成功了。但是我现在想部署到我的linux服务器，现在是成功启动了。我想问的是如何实现登录呢，我的linux是没有图形界面的，是必须需要装图形界面才能实现登录功能吗？就是登录接口是否能以参数的形式调用？
> 
> 您好 请问能给一个windows运行的教程以及文件吗 真的很想抢到票 感谢

你好，作者的首页的readme就已经很详细了，按照步骤来就可以了。

**Comment by rookieyjh** [comment]
> 感觉完全没有python基础还是看不懂 不过还是感谢

**Comment by ronething** [comment]
> 我想问的是如何实现登录呢，我的linux是没有图形界面的，是必须需要装图形界面才能实现登录功能吗？就是登录接口是否能以参数的形式调用？

目前是不支持的。这个更多的是适合个人电脑进行配置。不适合无桌面的服务器进行使用。如果你有相应开发能力，可以考虑进行协议登录/逆向对应逻辑，祝你好运~ 

>  如果直接调接口就只返回个login ok, 调购买接口返回buy ok 但是实际上是没有成功的

关于这个问题，因为是通过异步调用，所以接口直接返回了 ok 字样，实际上并没有成功。具体可看请求对应 api 的代码。

**Comment by rascal7x** [comment]
噢噢  感谢
