### ISSUE TITLE
同账号，挂两个不同的票价进行抢购

### ISSUE THREAD

**Issue by Redlove2015** [ronething/xiudong-selenium#34]
目前只能尝试使用两个账号去抢，好像网页只能登一个账号，同手机号再登录另外一个就会被踢出。 请问怎么能实现一个账号），同时抢两个价位的票呢？（观察到输入ORDER URL的时候都是只有第一个窗口在运行刷新购票，输入第二个ORDER URL 的时候也是会跳转到第一个窗口进行抢票）

**Comment by ronething** [comment]
这里其实涉及到两个问题。

1、多开程序如何使用同一个账号？

这里是用户凭证如何获取的问题。你不能重新登录，而是应该找到存储用户凭证的地方，然后多开的程序需要进行用户凭证 值的设置。点到为止，祝你好运~

2、单个程序如何进行多窗口抢票？

之前有考虑过 暂未实现。师傅可以考虑研究一下，期待你的 pr

PS: 还是可以考虑多账号抢票，不同账号抢到的概率**可能**高点。
