### ISSUE TITLE
http://127.0.0.1:9997/login,加载后直接login OK了吗，没有登录页面是为什么

### ISSUE THREAD

**Issue by pandaxue** [ronething/xiudong-selenium#38]
![1656517090595](https://user-images.githubusercontent.com/50400428/176478025-ad9cc28e-e934-4c3a-8ed6-65067a4a87d5.png)

**Comment by ronething** [comment]
你是在 selenium 里面进行请求访问，还是在系统浏览器进行访问。

**Comment by pandaxue** [comment]
> 你是在 selenium 里面进行请求访问，还是在系统浏览器进行访问。

在系统浏览器里面

**Comment by ronething** [comment]
可能要提供更多的上下文。例如运行起来之后，能看到 selenium 浏览器的页面吗。操作了什么，导致只是出现这个返回而没有看到 selenium 请求秀动登陆页。

**Comment by notailing-mouse** [comment]
![image](https://user-images.githubusercontent.com/75559145/176654409-e5de2132-c0d0-458e-b2f7-9a1f96c97675.png)
我这里程序能运行也没有报错，就是毫无反应

> 可能要提供更多的上下文。例如运行起来之后，能看到 selenium 浏览器的页面吗。操作了什么，导致只是出现这个返回而没有看到 selenium 请求秀动登陆页。

**Comment by pandaxue** [comment]
> 可能要提供更多的上下文。例如运行起来之后，能看到 selenium 浏览器的页面吗。操作了什么，导致只是出现这个返回而没有看到 selenium 请求秀动登陆页。

我没用这个居然抢到了刺猬的票今天，还是感谢你

**Comment by notailing-mouse** [comment]
> @notailing-mouse 可考虑参考 #35，如果是别的问题请提新的 issue，谢谢。

唔我那个是运行后毫无反应 也没有弹出Chrome

已解决，把python3改成python就好了……
