### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by jerbaning6** [ronething/xiudong-selenium#4]
ticketId 只能在点击立即购票后才能获取吗？可以出一下使用流程吗？没太弄明白，在浏览器输入 /buy 后只有在有票的情况下才能进入吗？

**Comment by ronething** [comment]
可以看一下这个 issue 哦 https://github.com/ronething/xiudong-selenium/issues/3

**Comment by ronething** [comment]
> 在浏览器输入 /buy 后只有在有票的情况下才能进入吗？

并不是，如果没有票，调用 buy 接口会自动进行刷新，直到显示有票为止(此时会停下来点击立即支付) 

先 close 有问题再提 issue
