### ISSUE TITLE
开抢时瞬间会提示操作太频繁了

### ISSUE THREAD

**Issue by MyHairAreNull** [ronething/xiudong-selenium#40]
**场景:**
热门城市的热门演出,(杭州刺猬)，开售时瞬间会提示操作太频繁了 440代码
捡漏时候偶尔已经正准备生成订单了，但是刷的一下也会被秒完并提示操作太频繁 440代码
菜鸡想到的解决方案:
在刷新的时候设置了sleep(float(random.random()/5))，测试了一下440出现的原因大概率是票售罄或者未开票。

**想请教下大佬:**
1.有没有什么方式可以提高一下抢票成功率的方式，少避免出现点击频繁的方法，比较热门的演出热门城市的话成功不高。
2.若开售时间为12:00时候，是设置成12:00还是12：03，看到有提前3s抢票机制
3.若出现440操作过快时候应该继续让它转圈圈还是自己手动刷新页面
![f858469e01b537b99f0182223a4b455](https://user-images.githubusercontent.com/56420915/176735229-161744ea-356c-49ee-9475-f2a57a78b22b.jpg)

**Comment by ronething** [comment]
> 1.有没有什么方式可以提高一下抢票成功率的方式，少避免出现点击频繁的方法，比较热门的演出热门城市的话成功不高。

可参考 #2 以及 #12 

>  2.若开售时间为12:00时候，是设置成12:00还是12：03，看到有提前3s抢票机制

根据以往经验，可以设置 12:00:00 之前的时间，例如 11:59:59, 3s 提前机制也可以自行修改

>  3.若出现440操作过快时候应该继续让它转圈圈还是自己手动刷新页面

本质上其实就是进行模拟点击，转圈圈的时候不需要手动刷新，继续点即可，至于点击频率的问题，可以尝试调一下 time.sleep()

最后，这个脚本我去年7月底完成开发并开始使用到12月底的时候，很多场次基本都是可以抢到的，后面的话可能由于大家看演出的热情以及抢票脚本的增多，导致即使你有脚本也不一定能抢到，可能也有风控限流的因素存在，当然也有运气成分(例如这里有人用手就抢到了 https://github.com/ronething/xiudong-selenium/issues/38#issuecomment-1171145823 )，像我 #12 说的，如果你有相应的开发能力，可以考虑逆向一下，难度其实不算大，点到为止，祝你好运~

**Comment by MyHairAreNull** [comment]
> 
了解了，感谢大佬的解答。也确定了优化和进一步学习的方向
