### ISSUE TITLE
怎么循环抢票？比如说每秒抢一次，针对那种暂时售罄但是可能有人退票的情况

### ISSUE THREAD

**Issue by xuquezi** [ronething/xiudong-selenium#41]
怎么循环抢票？比如说每秒抢一次，针对那种暂时售罄但是可能有人退票的情况

**Comment by ronething** [comment]
你可能想说的是每秒刷新购买页面？time.sleep 调整下时间即可。

**Comment by xuquezi** [comment]
还是不太懂，能在具体一点吗，我想循环的调用那个buy接口。针对可能有人退票的情况，不知道别人什么时候退票，所以要一直循环的调用buy接口

**Comment by xuquezi** [comment]
收到谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月6日(星期三) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ronething/xiudong-selenium] 怎么循环抢票？比如说每秒抢一次，针对那种暂时售罄但是可能有人退票的情况 (Issue #41)





 
程序本身的BUY接口就是设置了循环抢票的哦。您可以看代码，在按钮为已售罄的情况下是会不断刷新页面直到出现立即支付，然后点击
