### ISSUE TITLE
您好 现在我已经能够把脚本跑起来了 但是会由于下单速度过快导致购买失败 想问一下脚本的下单速度能够调整吗 感谢

### ISSUE THREAD

**Issue by rookieyjh** [ronething/xiudong-selenium#42]

**Comment by ronething** [comment]
可以的，下单速度的调整可以参考这里，https://github.com/ronething/xiudong-selenium/blob/6d857bbe4e04317cb365b9ee1e26112be79bc050/driver.py#L96-L97

捡漏的时间调整可以参考这里 https://github.com/ronething/xiudong-selenium/issues/41#issuecomment-1175985956

其实都是通过 time.sleep 调整即可，注意单位是秒

https://www.runoob.com/python/att-time-sleep.html

**Comment by ronething** [comment]
先 close 有问题可直接回复。
