### ISSUE TITLE
使用\buy接口时，浏览器“演出订单确认界面”报错‘system error’

### ISSUE THREAD

**Issue by taozihushuiguai** [ronething/xiudong-selenium#45]
前面的流程我都走过了，在试用buy接口时，发生问题
登陆后，比如执行http://127.0.0.1:9997/buy?event=event=177982&ticketId=ticketId=4d0555de9165462515e6376ef0162e0d&cron_time=2022%2007%2009%2023%2034%2000
时，浏览器会自动跳转到网址https://wap.showstart.com/pages/order/activity/confirm/confirm?sequence=event%3D177982&ticketId=ticketId%3D4d0555de9165462515e6376ef0162e0d&ticketNum=1&ioswx=1&terminal=app&from=singlemessag=e&isappinstalled=0
同时浏览器会出现报错，浏览器界面是空白的如下图所示，而脚本这边没有错误信息输出，看起来是正常的，执行窗口输出的也是buy OK！

![image](https://user-images.githubusercontent.com/65215448/178112679-65ff45be-a54a-4613-a49b-a967045af0d7.png)
![image](https://user-images.githubusercontent.com/65215448/178112678-d210b228-d238-452d-84ce-b95e829e2108.png)

**Comment by ronething** [comment]
@taozihushuiguai 

http://127.0.0.1:9997/buy?event=event=177982&ticketId=ticketId=4d0555de9165462515e6376ef0162e0d&cron_time=2022%2007%2009%2023%2034%2000

你的 event 多传了。`event=event=177982` 应该是 `event=177982`
