### ISSUE TITLE
第一步 网页出现空白data

### ISSUE THREAD

**Issue by yifanLon** [ronething/xiudong-selenium#46]
你好 大佬
按照readme 运行后还是会出现空白的data页面
 然后去看了issue3 尝试了一下 访问 http://127.0.0.1:9997/login 显示login ok 似乎不管在运行前访问 还是运行后访问 都不能跳转登陆页面 想问下这里的详细步骤 以及 访问http://127.0.0.1:9997/login 成功后 会有什么具体的效果呢 
非常感谢 如果能解答一下的话

**Comment by ronething** [comment]
你开的是系统的浏览器还是 selenium。也可以打开终端使用 `curl http://127.0.0.1:9997/login` 看看。
