### ISSUE TITLE
还是不懂怎么调用接口

### ISSUE THREAD

**Issue by oneeeeeeeeeee** [ronething/xiudong-selenium#5]
大大好，我想问一下如何调用接口。已经看了ISSUE#3，完成了登录找到了ticketid
然后不知道接下去要怎么做了（我是弱鸡[捂脸]）

**Comment by oneeeeeeeeeee** [comment]
尝试了一次 按您#3中的方式
抓取到了tickeid编辑进 http://127.0.0.1:9997/buy?event=111&ticketId=222 输入浏览器会进入抢票，但是不是很懂怎么设置定时，是需要在app.py里面编辑填入吗？
另外一个问题是如果秀动不允许网页购票，在点击立即购买后，还是无法抓包出ticketid，不知道该怎么办

**Comment by ronething** [comment]
> 但是不是很懂怎么设置定时，是需要在app.py里面编辑填入吗

https://github.com/ronething/xiudong-selenium/blob/bd8b4d68022c9d2895619200997393808842f94f/app.py#L61

https://github.com/ronething/xiudong-selenium/blob/bd8b4d68022c9d2895619200997393808842f94f/driver.py#L114-L115

多传一个 cron_time 参数即可，格式为(2022 05 05 22 00 00)，注意中间是空格(url 编码会自动替换为 %20), 类似这样

`http://127.0.0.1:9997/buy?event=111&ticketId=222&cron_time=2022 05 05 22 00 00`

> 另外一个问题是如果秀动不允许网页购票，在点击立即购买后，还是无法抓包出ticketid，不知道该怎么办

这一个其实也是可以解决的，可以简单参考一位大佬写的[这篇 blog](https://blog.marun.run/fiddler-shi-zhan-yi/)，不过稍微麻烦点，然后需要一定的抓包知识。

其实还有其他的方法，不过涉及到一些基本的 js 逆向知识，也许以后有机会我会开源一下。

就这样，先 close，有其他问题再开 issue。

**Comment by oneeeeeeeeeee** [comment]
谢谢大佬，膜拜！！！这就学习一下

**Comment by oneeeeeeeeeee** [comment]
经过昨天一天的奋战和学习，通过大佬推荐的文章，我终于找到了对应的ticketid怎么获取了。因为秀动更新了借口，所以文章不能完全适用，但是思路还是差不多的。通过fiddler的抓包和比较只允许APP购买和可网页购买的相关代码，我们实际要抓包的现在是https://wap.showstart.com/api/order/000JnT00lARM，后缀会因为不同票而不太一样，但是格式都差不多大概是00JxxxxtoolARM。修改里面,"sellTerminal":2,"将2改为1，即可把页面变成立即购买，修改完后再次运行，抓包相同的链接，里面就会详细的出现各个票的ticketid，按原来的方法就可以直接进入购票界面了

**Comment by ronething** [comment]
不错不错，祝你好运，有兴趣的话也可以看看帮忙改进下脚本 提提 pr 哦。

**Comment by oneeeeeeeeeee** [comment]
大佬说笑了，我纯新手刚入门，离看懂您的代码再改进还有很长的时间

**Comment by Ohihahaha** [comment]
> 经过昨天一天的奋战和学习，通过大佬推荐的文章，我终于找到了对应的ticketid怎么获取了。因为秀动更新了接口，所以文章不能完全适用，但是思路还是差不多的。通过fiddler的抓包和比较只允许APP购买和可网页购买的相关代码，我们实际要抓包的现在是[https://wap.showstart.com/api/order/000JnT00lARM，后缀会因为不同票而不太一样，但是格式都差不多大概是00JxxxxtoolARM。修改里面,"sellTerminal":2,"将2改为1，即可把页面变成立即购买，修改完后再次运行，抓包相同的链接，里面就会详细的出现各个票的ticketid，按原来的方法就可以直接进入购票界面了](https://wap.showstart.com/api/order/000JnT00lARM%EF%BC%8C%E5%90%8E%E7%BC%80%E4%BC%9A%E5%9B%A0%E4%B8%BA%E4%B8%8D%E5%90%8C%E7%A5%A8%E8%80%8C%E4%B8%8D%E5%A4%AA%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%A0%BC%E5%BC%8F%E9%83%BD%E5%B7%AE%E4%B8%8D%E5%A4%9A%E5%A4%A7%E6%A6%82%E6%98%AF00JxxxxtoolARM%E3%80%82%E4%BF%AE%E6%94%B9%E9%87%8C%E9%9D%A2,%22sellTerminal%22:2,%22%E5%B0%862%E6%94%B9%E4%B8%BA1%EF%BC%8C%E5%8D%B3%E5%8F%AF%E6%8A%8A%E9%A1%B5%E9%9D%A2%E5%8F%98%E6%88%90%E7%AB%8B%E5%8D%B3%E8%B4%AD%E4%B9%B0%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%AE%8C%E5%90%8E%E5%86%8D%E6%AC%A1%E8%BF%90%E8%A1%8C%EF%BC%8C%E6%8A%93%E5%8C%85%E7%9B%B8%E5%90%8C%E7%9A%84%E9%93%BE%E6%8E%A5%EF%BC%8C%E9%87%8C%E9%9D%A2%E5%B0%B1%E4%BC%9A%E8%AF%A6%E7%BB%86%E7%9A%84%E5%87%BA%E7%8E%B0%E5%90%84%E4%B8%AA%E7%A5%A8%E7%9A%84ticketid%EF%BC%8C%E6%8C%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%96%B9%E6%B3%95%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E5%85%A5%E8%B4%AD%E7%A5%A8%E7%95%8C%E9%9D%A2%E4%BA%86)

能不能详细解释一下这个步骤，看着有点懵。
要怎么改参数

**Comment by Joannerem** [comment]
> 动

大佬，我这里查的sellTerminal的字段是在“000JAx000000”里面。然后我暂停抓包了之后，进入编辑，修改了这个key之后，点击运行，没有任何变化。是哪一步错了呢？
![image](https://user-images.githubusercontent.com/98148981/170681010-0b1a4a77-bc40-4f50-91fb-38a83432078b.png)
<img width="2372" alt="image" src="https://user-images.githubusercontent.com/98148981/170681338-4ef97de2-fde6-4ccd-bbc4-9c05fb360030.png">
<img width="2358" alt="image" src="https://user-images.githubusercontent.com/98148981/170681412-ff7c2ea7-1e15-4f76-b9bf-0c2faf0a17da.png">

**Comment by oneeeeeeeeeee** [comment]
> > 经过昨天一天的奋战和学习，通过大佬推荐的文章，我终于找到了对应的ticketid怎么获取了。因为秀动更新了接口，所以文章不能完全适用，但是思路还是差不多的。通过fiddler的抓包和比较只允许APP购买和可网页购买的相关代码，我们实际要抓包的现在是[https://wap.showstart.com/api/order/000JnT00lARM，后缀会因为不同票而不太一样，但是格式都差不多大概是00JxxxxtoolARM。修改里面,"sellTerminal":2,"将2改为1，即可把页面变成立即购买，修改完后再次运行，抓包相同的链接，里面就会详细的出现各个票的ticketid，按原来的方法就可以直接进入购票界面了](https://wap.showstart.com/api/order/000JnT00lARM%EF%BC%8C%E5%90%8E%E7%BC%80%E4%BC%9A%E5%9B%A0%E4%B8%BA%E4%B8%8D%E5%90%8C%E7%A5%A8%E8%80%8C%E4%B8%8D%E5%A4%AA%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%A0%BC%E5%BC%8F%E9%83%BD%E5%B7%AE%E4%B8%8D%E5%A4%9A%E5%A4%A7%E6%A6%82%E6%98%AF00JxxxxtoolARM%E3%80%82%E4%BF%AE%E6%94%B9%E9%87%8C%E9%9D%A2,%22sellTerminal%22:2,%22%E5%B0%862%E6%94%B9%E4%B8%BA1%EF%BC%8C%E5%8D%B3%E5%8F%AF%E6%8A%8A%E9%A1%B5%E9%9D%A2%E5%8F%98%E6%88%90%E7%AB%8B%E5%8D%B3%E8%B4%AD%E4%B9%B0%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%AE%8C%E5%90%8E%E5%86%8D%E6%AC%A1%E8%BF%90%E8%A1%8C%EF%BC%8C%E6%8A%93%E5%8C%85%E7%9B%B8%E5%90%8C%E7%9A%84%E9%93%BE%E6%8E%A5%EF%BC%8C%E9%87%8C%E9%9D%A2%E5%B0%B1%E4%BC%9A%E8%AF%A6%E7%BB%86%E7%9A%84%E5%87%BA%E7%8E%B0%E5%90%84%E4%B8%AA%E7%A5%A8%E7%9A%84ticketid%EF%BC%8C%E6%8C%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%96%B9%E6%B3%95%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E5%85%A5%E8%B4%AD%E7%A5%A8%E7%95%8C%E9%9D%A2%E4%BA%86)
> 
> 能不能详细解释一下这个步骤，看着有点懵。 要怎么改参数

请先看那边作者推荐的Blog，学习一下如何使用fiddler。当你明白FIdder怎么使用之后，看那篇BLog以及我的表述就很容易明白步骤怎么做的

**Comment by oneeeeeeeeeee** [comment]
> > 动
> 
> 大佬，我这里查的sellTerminal的字段是在“000JAx000000”里面。然后我暂停抓包了之后，进入编辑，修改了这个key之后，

我不是很知道你的那个工具怎么用，我只会fiddler.....

**Comment by Joannerem** [comment]
> 经过昨天一天的奋战和学习，通过大佬推荐的文章，我终于找到了对应的ticketid怎么获取了。因为秀动更新了接口，所以文章不能完全适用，但是思路还是差不多的。通过fiddler的抓包和比较只允许APP购买和可网页购买的相关代码，我们实际要抓包的现在是[https://wap.showstart.com/api/order/000JnT00lARM，后缀会因为不同票而不太一样，但是格式都差不多大概是00JxxxxtoolARM。修改里面,"sellTerminal":2,"将2改为1，即可把页面变成立即购买，修改完后再次运行，抓包相同的链接，里面就会详细的出现各个票的ticketid，按原来的方法就可以直接进入购票界面了](https://wap.showstart.com/api/order/000JnT00lARM%EF%BC%8C%E5%90%8E%E7%BC%80%E4%BC%9A%E5%9B%A0%E4%B8%BA%E4%B8%8D%E5%90%8C%E7%A5%A8%E8%80%8C%E4%B8%8D%E5%A4%AA%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%A0%BC%E5%BC%8F%E9%83%BD%E5%B7%AE%E4%B8%8D%E5%A4%9A%E5%A4%A7%E6%A6%82%E6%98%AF00JxxxxtoolARM%E3%80%82%E4%BF%AE%E6%94%B9%E9%87%8C%E9%9D%A2,%22sellTerminal%22:2,%22%E5%B0%862%E6%94%B9%E4%B8%BA1%EF%BC%8C%E5%8D%B3%E5%8F%AF%E6%8A%8A%E9%A1%B5%E9%9D%A2%E5%8F%98%E6%88%90%E7%AB%8B%E5%8D%B3%E8%B4%AD%E4%B9%B0%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%AE%8C%E5%90%8E%E5%86%8D%E6%AC%A1%E8%BF%90%E8%A1%8C%EF%BC%8C%E6%8A%93%E5%8C%85%E7%9B%B8%E5%90%8C%E7%9A%84%E9%93%BE%E6%8E%A5%EF%BC%8C%E9%87%8C%E9%9D%A2%E5%B0%B1%E4%BC%9A%E8%AF%A6%E7%BB%86%E7%9A%84%E5%87%BA%E7%8E%B0%E5%90%84%E4%B8%AA%E7%A5%A8%E7%9A%84ticketid%EF%BC%8C%E6%8C%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%96%B9%E6%B3%95%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E5%85%A5%E8%B4%AD%E7%A5%A8%E7%95%8C%E9%9D%A2%E4%BA%86)

麻烦再请教一下~我看request里terminal的值是wap，response里的才是2。而我好像只能改request的（纯小白orz），改了之后就报错了
<img width="1465" alt="8583910A-6A4C-4886-A6F9-5FE1B9D71950" src="https://user-images.githubusercontent.com/98148981/171269796-e820555d-28f2-47a2-a006-c5acb30aa071.png">

**Comment by oneeeeeeeeeee** [comment]
> > > 经过昨天一天的奋战和学习，通过大佬推荐的文章，我终于找到了对应的ticketid怎么获取了。因为秀动更新了接口，所以文章不能完全适用，但是思路还是差不多的。通过fiddler的抓包和比较只允许APP购买和可网页购买的相关代码，我们实际要抓包的现在是[https://wap.showstart.com/api/order/000JnT00lARM，后缀会因为不同票而不太一样，但是格式都差不多大概是00JxxxxtoolARM。修改里面,"sellTerminal":2,"将2改为1，即可把页面变成立即购买，修改完后再次运行，抓包相同的链接，里面就会详细的出现各个票的ticketid，按原来的方法就可以直接进入购票界面了](https://wap.showstart.com/api/order/000JnT00lARM%EF%BC%8C%E5%90%8E%E7%BC%80%E4%BC%9A%E5%9B%A0%E4%B8%BA%E4%B8%8D%E5%90%8C%E7%A5%A8%E8%80%8C%E4%B8%8D%E5%A4%AA%E4%B8%80%E6%A0%B7%EF%BC%8C%E4%BD%86%E6%98%AF%E6%A0%BC%E5%BC%8F%E9%83%BD%E5%B7%AE%E4%B8%8D%E5%A4%9A%E5%A4%A7%E6%A6%82%E6%98%AF00JxxxxtoolARM%E3%80%82%E4%BF%AE%E6%94%B9%E9%87%8C%E9%9D%A2,%22sellTerminal%22:2,%22%E5%B0%862%E6%94%B9%E4%B8%BA1%EF%BC%8C%E5%8D%B3%E5%8F%AF%E6%8A%8A%E9%A1%B5%E9%9D%A2%E5%8F%98%E6%88%90%E7%AB%8B%E5%8D%B3%E8%B4%AD%E4%B9%B0%EF%BC%8C%E4%BF%AE%E6%94%B9%E5%AE%8C%E5%90%8E%E5%86%8D%E6%AC%A1%E8%BF%90%E8%A1%8C%EF%BC%8C%E6%8A%93%E5%8C%85%E7%9B%B8%E5%90%8C%E7%9A%84%E9%93%BE%E6%8E%A5%EF%BC%8C%E9%87%8C%E9%9D%A2%E5%B0%B1%E4%BC%9A%E8%AF%A6%E7%BB%86%E7%9A%84%E5%87%BA%E7%8E%B0%E5%90%84%E4%B8%AA%E7%A5%A8%E7%9A%84ticketid%EF%BC%8C%E6%8C%89%E5%8E%9F%E6%9D%A5%E7%9A%84%E6%96%B9%E6%B3%95%E5%B0%B1%E5%8F%AF%E4%BB%A5%E7%9B%B4%E6%8E%A5%E8%BF%9B%E5%85%A5%E8%B4%AD%E7%A5%A8%E7%95%8C%E9%9D%A2%E4%BA%86)
> > 
> > 
> > 麻烦再请教一下~我看request里terminal的值是wap，response里的才是2。而我好像只能改request的（纯小白orz），改了之后就报错了 <img alt="8583910A-6A4C-4886-A6F9-5FE1B9D71950" width="1465" src="https://user-images.githubusercontent.com/98148981/171269796-e820555d-28f2-47a2-a006-c5acb30aa071.png">
> 
> 在JSON里面看得到的，应该是在RAW里面修改才对

参数是叫sellTerminal

**Comment by smallpang** [comment]
大佬们，我按照上面的blog，修改了sellTerminal里的值，能够将原本的“仅在app内购买”按钮修改成“立即购票”，但是我点击“立即购票”，无法像之前那样，唤起购票按钮，这样就无法获取到ticketid，我也对比可以在web端购买的链接，按照那篇blog对比type值，也没有找到不同的地方，请问应该怎么办呐？

**Comment by smallpang** [comment]
大佬们，我按照上面的blog，修改了sellTerminal里的值，能够将原本的“仅在app内购买”按钮修改成“立即购票”，但是我点击“立即购票”，无法像之前那样，唤起购票按钮，这样就无法获取到ticketid，我也对比可以在web端购买的链接，按照那篇blog对比type值，也没有找到不同的地方，请问应该怎么办呐？

**Comment by oneeeeeeeeeee** [comment]
> 大佬们，我按照上面的blog，修改了sellTerminal里的值，能够将原本的“仅在app内购买”按钮修改成“立即购票”，但是我点击“立即购票”，无法像之前那样，唤起购票按钮，这样就无法获取到ticketid，我也对比可以在web端购买的链接，按照那篇blog对比type值，也没有找到不同的地方，请问应该怎么办呐？

你忘记取消断点了，两种方法，改完取消断点或者改完之后点击立即购买的时候回去继续放行

**Comment by smallpang** [comment]
> 你忘记取消断点了，两种方法，改完取消断点或者改完之后点击立即购买的时候回去继续放行

大佬。不行，我没有打断点，之前打断点试过，后来我取消了，现在依然唤起不了支付按钮，就是下面这个界面，我点不开。
![image](https://user-images.githubusercontent.com/33652387/172843787-0128684a-e7b2-42e7-b8cf-73998ec0b00e.png)

能麻烦您试试吗？
![image](https://user-images.githubusercontent.com/33652387/172844698-a9c420f7-9d28-4392-af79-8624459335f9.png)

**Comment by lyyww** [comment]
用burp亲测可行，打完断点，修改完response的sell terminal后，全部放行

**Comment by oneeeeeeeeeee** [comment]
> 用burp亲测可行，打完断点，修改完response的sell terminal后，全部放行

主要是我不知道你怎么做的，我用Fidder做的是完全没问题的。近期的如姜云升，夏日企划等，我都是能修改获取的

**Comment by oneeeeeeeeeee** [comment]
> > 你忘记取消断点了，两种方法，改完取消断点或者改完之后点击立即购买的时候回去继续放行
> 
> 大佬。不行，我没有打断点，之前打断点试过，后来我取消了，现在依然唤起不了支付按钮，就是下面这个界面，我点不开。 ![image](https://user-images.githubusercontent.com/33652387/172843787-0128684a-e7b2-42e7-b8cf-73998ec0b00e.png)
> 
> 能麻烦您试试吗？ ![image](https://user-images.githubusercontent.com/33652387/172844698-a9c420f7-9d28-4392-af79-8624459335f9.png)

主要是我不知道你怎么做的，我用Fidder做的是完全没问题的。近期的如姜云升，夏日企划等，我都是能修改获取的

**Comment by smallpang** [comment]
> 主要是我不知道你怎么做的，我用Fidder做的是完全没问题的。近期的如姜云升，夏日企划等，我都是能修改获取的
大佬们，我明明就是打了断点，修改了sellTerminal的值然后放行了，还是不行....我不知道是哪步出错了，能方便通过邮箱加个微信or其他联系方式指点一下我吗？跪求Orz....我的邮箱是penggj98@163.com

**Comment by smallpang** [comment]
> > > 你忘记取消断点了，两种方法，改完取消断点或者改完之后点击立即购买的时候回去继续放行
> > 
> > 
> > 大佬。不行，我没有打断点，之前打断点试过，后来我取消了，现在依然唤起不了支付按钮，就是下面这个界面，我点不开。 ![image](https://user-images.githubusercontent.com/33652387/172843787-0128684a-e7b2-42e7-b8cf-73998ec0b00e.png)
> > 能麻烦您试试吗？ ![image](https://user-images.githubusercontent.com/33652387/172844698-a9c420f7-9d28-4392-af79-8624459335f9.png)
> 
> 主要是我不知道你怎么做的，我用Fidder做的是完全没问题的。近期的如姜云升，夏日企划等，我都是能修改获取的

大佬们，我明明就是打了断点，修改了sellTerminal的值然后放行了，还是不行....我不知道是哪步出错了，能方便通过邮箱加个微信or其他联系方式指点一下我吗？跪求Orz....我的邮箱是[penggj98@163.com](mailto:penggj98@163.com)

**Comment by Redlove2015** [comment]
实测 目前在抢夏企的17号厦门，使用 chrome 登录秀动之后
ELEMENT
document.querySelector("body > script:nth-child(2)")
/html/body/script[1]


这个位置直接就显示了 ID,ticketName
我是直接搜索的TICKET 看到

**Comment by ronething** [comment]
关于这个问题 还可以不通过拦截响应解决

访问 www.showstart.com

注意原先访问的是 wap.showstart.com 域名不用

然后点击场次 可以直接通过开发者工具抓包获取对应 ticketId

**Comment by MyHairAreNull** [comment]
大佬，你好。测试几个开售的演出时候遇到问题，场景：【演出开票时间12:00】 ,两台电脑pycharm设置的开抢时间分别时【11:59:57】和【12:00:03】.(因为延迟3秒抢票故延迟)，但是到点没有进行自动抢票的操作，只有在把时间往后推迟1~2分钟的时候才能到点开抢。是因为开售一瞬间的流量太大了，请求不到后台了吗？

console log 输出:(到开抢时间点时)
['CDwindow-E211D11A1250D4581E28E024DBBAB248']
127.0.0.1 - - [29/Jun/2022 14:00:53] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by rookieyjh** [comment]
> 实测 目前在抢夏企的17号厦门，使用 chrome 打开秀动之后 F12- ELEMENT 这个路劲 document.querySelector("body > script:nth-child(2)") /html/body/script[1]
> 
> 这个位置直接就显示了 ID,ticketName 我是直接搜索的TICKET 看到

哥们儿我想问一下 您用这个代码能抢到夏企的门票吗 我总是下单速度过快不知道如何调节
