### ISSUE TITLE
不进行按钮点击

### ISSUE THREAD

**Issue by Joannerem** [ronething/xiudong-selenium#53]
进入到抢票页面了，但是不会产生点击行为，定时也用不了。但是py里没有报错，大佬能帮忙看看是为什么么
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/98148981/184397095-e93fe7d1-d721-475a-b7ca-5c6958965d66.png">

**Comment by Joannerem** [comment]
就一直卡在这个页面，也不刷新
<img width="561" alt="image" src="https://user-images.githubusercontent.com/98148981/184397337-f03569a4-5dd4-48fc-b8f7-2dc332dd78ec.png">

**Comment by X1a0hu** [comment]
我也遇到了这个问题 请问是怎么解决的
