### ISSUE TITLE
Detected factory 'create_app' in module

### ISSUE THREAD

**Issue by smallpang** [ronething/xiudong-selenium#56]
FLASK_APP = main.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder H:/秀动/xiudong-selenium-main
G:\Anaconda\python.exe -m flask run
 * Serving Flask app 'main.py' (lazy loading)
 * Environment: development
 * Debug mode: off
Usage: __main__.py run [OPTIONS]

Error: Detected factory 'create_app' in module 'xiudong-selenium-main.main', but could not call it without arguments. Use "FLASK_APP='xiudong-selenium-main.main:create_app(args)'" to specify arguments.

大佬，使用新版本的时候，遇到这个问题，一运行main.py就报错。在网上也没有找到解决办法，能麻烦您帮忙看看是怎么回事吗？

**Comment by ronething** [comment]
可以使用 `python3 main.py`, 而不是 `flask run`

**Comment by smallpang** [comment]
我在cmd里和terminal里都试了，不行诶，我尝试输出一个值，可是程序好像都没有进main里面，没有执行main.py
![QQ图片20221109094035](https://user-images.githubusercontent.com/33652387/200716141-1f083d8e-e30d-4d9d-8061-15ac8e713c29.png)

**Comment by ronething** [comment]
可以参考这里 https://github.com/ronething/xiudong-selenium/issues/38#issuecomment-1171175782

**Comment by ronething** [comment]
ok，有问题再提 issue

**Comment by oklbuy331** [comment]
根据Flaks作者的博文[https://www.twilio.com/blog/how-run-flask-application](url)，运行Flask有好几种方式，issue中采用的方式是：`flask run`。命令行`flask run`会去寻找系统环境变量`FLASK_APP`指定的文件（__init__.py或者app.py），找到其中运行`create_app(::params)`函数的地方，然后初始化Flask app。 
但是，在本repository中的`main.py`中line10 运行`create_app`函数需要提供参数：
```python
    app = create_app(driver, pool)
```
所以，这里的问题应该是：你指定的系统环境变量FLASK_APP = main.py没有参数。
解决方法应该是这样：
1. cd到mian.py所在目录
2. 进入命令行（假设你是Linux），并声明系统变量，运行Flask app：
```bash
export FLASK_APP="main:create_app(::params)"
flask run
```
问题是：要想用这种方式运行app，`create_app`的参数不能是变量，需要重构一下代码。
