### ISSUE TITLE
抢票记录

### ISSUE THREAD

**Issue by ronething** [ronething/xiudong-selenium#6]
有抢到票的小伙伴可以考虑发一下记录。记得打码个人信息(手机号等)。

**Comment by UNICKON** [comment]
现在热门场次似乎只显示打开app购买了

**Comment by Joannerem** [comment]
> 7点12分 抢到了！
> 
> <img alt="image" width="1350" src="https://user-images.githubusercontent.com/71202919/167879526-175352ef-ec15-4eb4-a0e2-d67db600f12c.png">

求问，怎么拿ticketid的啊？网页打不开选择价格的面板

**Comment by connorfa** [comment]
支付前要绑定人，卡在这一步，然后就没办法支付了。关于这个问题，请问你有什么思路或者方法解决？

**Comment by Kelinhy** [comment]
hi bro，请问 ticketId 以及 event 是如何找到的？

**Comment by MyHairAreNull** [comment]
大佬，你好。测试几个开售的演出时候遇到问题，场景：【演出开票时间12:00】 ,两台电脑pycharm设置的开抢时间分别时【11:59:57】和【12:00:03】.(因为延迟3秒抢票故延迟)，但是到点没有进行自动抢票的操作，只有在把时间往后推迟1~2分钟的时候才能到点开抢。是因为开售一瞬间的流量太大了，请求不到后台了吗？

console log 输出:(到开抢时间点时)
['CDwindow-E211D11A1250D4581E28E024DBBAB248']
127.0.0.1 - - [29/Jun/2022 14:00:53] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by taozihushuiguai** [comment]
<img width="199" alt="1657523493360" src="https://user-images.githubusercontent.com/65215448/178208531-4681db5a-c4ce-45ce-bca8-a4a988a0eef5.png">
抢到了逃跑计划！！！

**Comment by findu201** [comment]
> <img alt="1657523493360" width="199" src="https://user-images.githubusercontent.com/65215448/178208531-4681db5a-c4ce-45ce-bca8-a4a988a0eef5.png">
> 
> 抢到了逃跑计划！！！

我也是抢逃跑！！学生票没抢到

**Comment by taozihushuiguai** [comment]
> 



> > <img alt="1657523493360" width="199" src="https://user-images.githubusercontent.com/65215448/178208531-4681db5a-c4ce-45ce-bca8-a4a988a0eef5.png">
> > 抢到了逃跑计划！！！
> 
> 我也是抢逃跑！！学生票没抢到

哎 其实原价不用抢 后面很多啦！被饥饿营销了！
