### ISSUE TITLE
请问是不支持macos吗

### ISSUE THREAD

**Issue by zyp1573** [ronething/xiudong-selenium#62]
### 问题描述

已安装最新版chrome
已安装chromedriver
<img width="570" alt="image" src="https://user-images.githubusercontent.com/49891496/223980136-e8690c7c-72cf-4776-8043-883ba53648aa.png">
安装了依赖
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/49891496/223980509-4c32eab5-0168-4e6c-bf2e-0b97631dc90b.png">
启动报错
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/49891496/223980587-e9912305-c97c-47b1-a1cb-0a84dcf21203.png">

**Comment by ronething** [comment]
看起来是 driver 的路径问题，refer: https://github.com/ronething/xiudong-selenium/issues/23#issuecomment-1153239551

**Comment by zyp1573** [comment]
> @zyp1573 看起来是 chromedriver 的路径问题，参考： [#23 （评论）](https://github.com/ronething/xiudong-selenium/issues/23#issuecomment-1153239551)

好的 我试一下

**Comment by zyp1573** [comment]
> @zyp1573 看起来是 chromedriver 的路径问题，refer: [#23 (comment)](https://github.com/ronething/xiudong-selenium/issues/23#issuecomment-1153239551)

已经解决了 把Chromedriver移动到一个固定的位置   然后修改driver.py L29到那个位置就好了

macos建议到/usr/local/bin

`sudo MV Chromedriver /usr/local/bin`

**Comment by zyp1573** [comment]
> @zyp1573 看起来是 chromedriver 的路径问题，refer: [#23 (comment)](https://github.com/ronething/xiudong-selenium/issues/23#issuecomment-1153239551)

谢谢大佬
