### ISSUE TITLE
设置了定时但是到了时间没有任何反应？

### ISSUE THREAD

**Issue by wangjunrong09** [ronething/xiudong-selenium#63]
### 问题描述
![image](https://user-images.githubusercontent.com/55369939/226227938-879b3e03-7226-41d7-ad36-a88aefa7c4cc.png)

**Comment by ronething** [comment]
@wangjunrong09 请先确认下需要需要选择观演人，需要则需要多传一个 need_select 参数

**Comment by wangjunrong09** [comment]
欧克，明白了，谢大佬~
