### ISSUE TITLE
设置定时后，时间到了没有反应

### ISSUE THREAD

**Issue by cjd9658** [ronething/xiudong-selenium#64]
![99ccaaa6ba513d7c0e6fb33ffabcc49](https://user-images.githubusercontent.com/89057402/227715946-fb411684-3f39-4714-86af-97ac57a4fe23.png)

**Comment by ronething** [comment]
@cjd9658 确保是否需要选择观演人，不需要则不要传 need_select 参数

**Comment by cjd9658** [comment]
> 

不需要选择，但是没传need_select也是没反应

**Comment by ronething** [comment]
可以考虑提供最小可复现的步骤，不然没办法排查问题。

**Comment by cjd9658** [comment]
> 可以考虑提供最小可复现的步骤，不然没办法排查问题。



> 可以考虑提供最小可复现的步骤，不然没办法排查问题。

能够进入到else定时分支，但是t1 = time.mktime(time.strptime(start_time, "%Y %m %d %H %M %S"))，要打印这个t1就打印不出了
