### ISSUE TITLE
调用buy接口几秒钟就出现错误

### ISSUE THREAD

**Issue by Joker-zZZZ** [ronething/xiudong-selenium#68]
请问大佬这种情况怎么解决呢？调用buy接口正常几秒就出现这个问题
![image](https://github.com/ronething/xiudong-selenium/assets/127177530/83323003-9b05-4162-a6b7-8bd1c6f0b090)

**Comment by ronething** [comment]
理论上是服务端返回的错误，表示请求频繁。解决方法的话，可能要调整一下请求发起的频率，或者说点击立即支付的频率，可以参考仓库之前的 issue 或者直接看下代码。此项目现在抢到票的概率不高，仅作为学习使用，谢谢。
