### ISSUE TITLE
定时设置之后并没有打印“开始抢票”

### ISSUE THREAD

**Issue by DamianDicky** [ronething/xiudong-selenium#71]
![65144d9756a8e5397fa7df7608796dd](https://github.com/ronething/xiudong-selenium/assets/138894960/b8012aba-e04e-4fc1-9253-0cd9d05b8b02)

输入的网址添加了cron_time的参数，确定了不需要勾选观影人，不需要传入need_select参数，但过了时间就会卡在提价订单的页面，并没有生成订单

**Comment by ronething** [comment]
https://github.com/ronething/xiudong-selenium/issues/64 可以看下是否是一样的问题，
