### ISSUE TITLE
小白求问，运行不了

### ISSUE THREAD

**Issue by Eririchinnya** [ronething/xiudong-selenium#77]
运行到浏览器执行http://127.0.0.1:9997/login之后，会直接未连接到互联网

![OQ{%`P{FF O_L11SC6DETHJ](https://github.com/ronething/xiudong-selenium/assets/142829736/3199fb5b-8cee-4dfa-9035-638e4780f690)

**Comment by ronething** [comment]
先看看能不能正常访问这个地址？

**Comment by Eririchinnya** [comment]
谢谢大佬回复，已经解决了，今天去抢我喜欢的live，虽然没抢到，但是还是很感谢大佬的分享！

**Comment by ronething** [comment]
不客气，现在用这个确实概率不高的。很多人都会有脚本。祝你下次好运。
